version: '3.3'

services:

  postgres:
    image: postgres:11.5-alpine
    container_name: first_pet_project
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=first_pet_project
      - POSTGRES_PASSWORD=
    ports:
      - "127.0.0.1:24012:5432"
    volumes:
      - first_pet_project_postgres_data:/var/lib/postgresql/data/

volumes:
  first_pet_project_postgres_data:
