version: '3.3'

services:

  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pet_project
      - POSTGRES_PASSWORD=
    ports:
      - "127.0.0.1:24012:5432"
    volumes:
      - db_local_data:/var/lib/postgresql/data/

volumes:
  db_local_data:
